stages:
  data_ingestion:
    cmd: python src/TeaDiseaseClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/TeaDiseaseClassifier/pipeline/stage_01_data_ingestion.py.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Tea_Leaf_Disease


  prepare_base_model:
    cmd: python src/TeaDiseaseClassifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/TeaDiseaseClassifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model



  training:
    cmd: python src/TeaDiseaseClassifier/pipeline/stage_03_training_model.py
    deps:
      - src/TeaDiseaseClassifier/pipeline/stage_03_training_model.py
      - src/TeaDiseaseClassifier/components/prepare_callback.py
      - config/config.yaml
      - artifacts/data_ingestion/Tea_Leaf_Disease
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5


  

  evaluation:
    cmd: python src/TeaDiseaseClassifier/pipeline/stage_04_evaluation.py
    deps:
      - src/TeaDiseaseClassifier/pipeline/stage_04_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/Tea_Leaf_Disease
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false